# Generated by Django 5.2.6 on 2025-09-16 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="search_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_sales_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="trending_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="event",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["trending_score"], name="events_trendin_c5ed5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_trending"], name="events_is_tren_873e25_idx"
            ),
        ),
    ]
